version: "3.8"

services:
  product-service:
    build: ./product-service
    ports:
      - "5001:5001"

  order-service:
    build: ./order-service
    ports:
      - "5002:5002"
    depends_on:
      - product-service

  payment-service:
    build: ./payment-service
    ports:
      - "5003:5003"
    depends_on:
      - order-service

  user-service:
    build: ./user-service
    ports:
      - "5004:5004"
    depends_on:
      - payment-service

  inventory-service:
    build: ./inventory-service
    ports:
      - "5005:5005"
    depends_on:
      - product-service

  dashboard-service:
    build: ./dashboard-service
    ports:
      - "8080:80"
